#!/bin/bash

# this export is a must for all cron jobs that need to use GUI to use the correct display
export DISPLAY=:0

battery_level="$(acpi -b | grep -v "Charging" | grep -P -o '([0-9]+(?=%))')"
LOW_BATTERY=15
CRITICAL_BATTERY=5
BATTERY_MAX=100

if [[ -z "$battery_level" ]]; then
    exit 0
fi


if [[ "$battery_level" -le "$LOW_BATTERY" ]]; then
    notify-send -t 15000 -u normal "Low Battery" "Battery Level Is ${battery_level}%"
    exit 0
fi
if [[ "$battery_level" -le "$CRITICAL_BATTERY" ]]; then
    notify-send -t 15000 -u critical "Critical Battery" "Battery Level Is ${battery_level}%"
    exit 0
fi
if [[ "$BATTERY_MAX" -eq "100" ]]; then
    notify-senf -t 15000 -u normal "Battery Fully Charged" "Battery Level Is ${battery_level}%"
    exit 0
fi
