#!/bin/bash

export DISPLAY=:0

# gets current battery charge and used to check if battery is currently charging or not
check_charging="$(acpi -b | grep -v "Charging" | grep -Po '([0-9]+(?=%))')"

# checks if battery is cahrging or not
if [[ -z "$check_charging" ]]; then
    exit 0
fi

# runs python script and grabs value from script
run_script="$(/usr/bin/python3 /usr/local/bin/battery-notify.py 2>&1 > /dev/null)"

# runs if it did recive a value from pyhton script
if [[ "$run_script" == "Low" ]]; then
    notify-send -t 15000 -u normal "Low Battery" "Battery Level Is ${check_charging}%"
    exit 0
fi
if [[ "$run_script" == "Critical" ]]; then
    notify-send -t 15000 -u critical "Critical Battery" "Battery Level Is ${check_charging}%"
    exit 0
fi
if [[ "$run_script" == "Full" ]]; then
    notify-send -t 15000 -u normal "Full Battery" "Battery Level Is ${check_charging}%"
    exit 0
fi

exit 0
